//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pruebas.ServicioUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.academico.ulasalle.com", ConfigurationName="ServicioUsuario.usuario")]
    public interface usuario {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://services.academico.ulasalle.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Pruebas.ServicioUsuario.sesionValidaResponse sesionValida(Pruebas.ServicioUsuario.sesionValidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Pruebas.ServicioUsuario.sesionValidaResponse> sesionValidaAsync(Pruebas.ServicioUsuario.sesionValidaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://services.academico.ulasalle.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Pruebas.ServicioUsuario.getInformacionResponse getInformacion(Pruebas.ServicioUsuario.getInformacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Pruebas.ServicioUsuario.getInformacionResponse> getInformacionAsync(Pruebas.ServicioUsuario.getInformacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://services.academico.ulasalle.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Pruebas.ServicioUsuario.getPeriodosResponse getPeriodos(Pruebas.ServicioUsuario.getPeriodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Pruebas.ServicioUsuario.getPeriodosResponse> getPeriodosAsync(Pruebas.ServicioUsuario.getPeriodosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://services.academico.ulasalle.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Pruebas.ServicioUsuario.setContrasenaResponse setContrasena(Pruebas.ServicioUsuario.setContrasenaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Pruebas.ServicioUsuario.setContrasenaResponse> setContrasenaAsync(Pruebas.ServicioUsuario.setContrasenaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sesionValidaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sesionValida", Namespace="http://services.academico.ulasalle.com", Order=0)]
        public Pruebas.ServicioUsuario.sesionValidaRequestBody Body;
        
        public sesionValidaRequest() {
        }
        
        public sesionValidaRequest(Pruebas.ServicioUsuario.sesionValidaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.academico.ulasalle.com")]
    public partial class sesionValidaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public sesionValidaRequestBody() {
        }
        
        public sesionValidaRequestBody(string dni, string password) {
            this.dni = dni;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sesionValidaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sesionValidaResponse", Namespace="http://services.academico.ulasalle.com", Order=0)]
        public Pruebas.ServicioUsuario.sesionValidaResponseBody Body;
        
        public sesionValidaResponse() {
        }
        
        public sesionValidaResponse(Pruebas.ServicioUsuario.sesionValidaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.academico.ulasalle.com")]
    public partial class sesionValidaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool sesionValidaReturn;
        
        public sesionValidaResponseBody() {
        }
        
        public sesionValidaResponseBody(bool sesionValidaReturn) {
            this.sesionValidaReturn = sesionValidaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInformacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInformacion", Namespace="http://services.academico.ulasalle.com", Order=0)]
        public Pruebas.ServicioUsuario.getInformacionRequestBody Body;
        
        public getInformacionRequest() {
        }
        
        public getInformacionRequest(Pruebas.ServicioUsuario.getInformacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.academico.ulasalle.com")]
    public partial class getInformacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        public getInformacionRequestBody() {
        }
        
        public getInformacionRequestBody(string dni) {
            this.dni = dni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInformacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInformacionResponse", Namespace="http://services.academico.ulasalle.com", Order=0)]
        public Pruebas.ServicioUsuario.getInformacionResponseBody Body;
        
        public getInformacionResponse() {
        }
        
        public getInformacionResponse(Pruebas.ServicioUsuario.getInformacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.academico.ulasalle.com")]
    public partial class getInformacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getInformacionReturn;
        
        public getInformacionResponseBody() {
        }
        
        public getInformacionResponseBody(string getInformacionReturn) {
            this.getInformacionReturn = getInformacionReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPeriodosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPeriodos", Namespace="http://services.academico.ulasalle.com", Order=0)]
        public Pruebas.ServicioUsuario.getPeriodosRequestBody Body;
        
        public getPeriodosRequest() {
        }
        
        public getPeriodosRequest(Pruebas.ServicioUsuario.getPeriodosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.academico.ulasalle.com")]
    public partial class getPeriodosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        public getPeriodosRequestBody() {
        }
        
        public getPeriodosRequestBody(string dni) {
            this.dni = dni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPeriodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPeriodosResponse", Namespace="http://services.academico.ulasalle.com", Order=0)]
        public Pruebas.ServicioUsuario.getPeriodosResponseBody Body;
        
        public getPeriodosResponse() {
        }
        
        public getPeriodosResponse(Pruebas.ServicioUsuario.getPeriodosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.academico.ulasalle.com")]
    public partial class getPeriodosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPeriodosReturn;
        
        public getPeriodosResponseBody() {
        }
        
        public getPeriodosResponseBody(string getPeriodosReturn) {
            this.getPeriodosReturn = getPeriodosReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setContrasenaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setContrasena", Namespace="http://services.academico.ulasalle.com", Order=0)]
        public Pruebas.ServicioUsuario.setContrasenaRequestBody Body;
        
        public setContrasenaRequest() {
        }
        
        public setContrasenaRequest(Pruebas.ServicioUsuario.setContrasenaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.academico.ulasalle.com")]
    public partial class setContrasenaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nuevaContrasena;
        
        public setContrasenaRequestBody() {
        }
        
        public setContrasenaRequestBody(string dni, string contrasena, string nuevaContrasena) {
            this.dni = dni;
            this.contrasena = contrasena;
            this.nuevaContrasena = nuevaContrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setContrasenaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setContrasenaResponse", Namespace="http://services.academico.ulasalle.com", Order=0)]
        public Pruebas.ServicioUsuario.setContrasenaResponseBody Body;
        
        public setContrasenaResponse() {
        }
        
        public setContrasenaResponse(Pruebas.ServicioUsuario.setContrasenaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.academico.ulasalle.com")]
    public partial class setContrasenaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setContrasenaReturn;
        
        public setContrasenaResponseBody() {
        }
        
        public setContrasenaResponseBody(string setContrasenaReturn) {
            this.setContrasenaReturn = setContrasenaReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface usuarioChannel : Pruebas.ServicioUsuario.usuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class usuarioClient : System.ServiceModel.ClientBase<Pruebas.ServicioUsuario.usuario>, Pruebas.ServicioUsuario.usuario {
        
        public usuarioClient() {
        }
        
        public usuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public usuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public usuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public usuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pruebas.ServicioUsuario.sesionValidaResponse Pruebas.ServicioUsuario.usuario.sesionValida(Pruebas.ServicioUsuario.sesionValidaRequest request) {
            return base.Channel.sesionValida(request);
        }
        
        public bool sesionValida(string dni, string password) {
            Pruebas.ServicioUsuario.sesionValidaRequest inValue = new Pruebas.ServicioUsuario.sesionValidaRequest();
            inValue.Body = new Pruebas.ServicioUsuario.sesionValidaRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.password = password;
            Pruebas.ServicioUsuario.sesionValidaResponse retVal = ((Pruebas.ServicioUsuario.usuario)(this)).sesionValida(inValue);
            return retVal.Body.sesionValidaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pruebas.ServicioUsuario.sesionValidaResponse> Pruebas.ServicioUsuario.usuario.sesionValidaAsync(Pruebas.ServicioUsuario.sesionValidaRequest request) {
            return base.Channel.sesionValidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pruebas.ServicioUsuario.sesionValidaResponse> sesionValidaAsync(string dni, string password) {
            Pruebas.ServicioUsuario.sesionValidaRequest inValue = new Pruebas.ServicioUsuario.sesionValidaRequest();
            inValue.Body = new Pruebas.ServicioUsuario.sesionValidaRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.password = password;
            return ((Pruebas.ServicioUsuario.usuario)(this)).sesionValidaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pruebas.ServicioUsuario.getInformacionResponse Pruebas.ServicioUsuario.usuario.getInformacion(Pruebas.ServicioUsuario.getInformacionRequest request) {
            return base.Channel.getInformacion(request);
        }
        
        public string getInformacion(string dni) {
            Pruebas.ServicioUsuario.getInformacionRequest inValue = new Pruebas.ServicioUsuario.getInformacionRequest();
            inValue.Body = new Pruebas.ServicioUsuario.getInformacionRequestBody();
            inValue.Body.dni = dni;
            Pruebas.ServicioUsuario.getInformacionResponse retVal = ((Pruebas.ServicioUsuario.usuario)(this)).getInformacion(inValue);
            return retVal.Body.getInformacionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pruebas.ServicioUsuario.getInformacionResponse> Pruebas.ServicioUsuario.usuario.getInformacionAsync(Pruebas.ServicioUsuario.getInformacionRequest request) {
            return base.Channel.getInformacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pruebas.ServicioUsuario.getInformacionResponse> getInformacionAsync(string dni) {
            Pruebas.ServicioUsuario.getInformacionRequest inValue = new Pruebas.ServicioUsuario.getInformacionRequest();
            inValue.Body = new Pruebas.ServicioUsuario.getInformacionRequestBody();
            inValue.Body.dni = dni;
            return ((Pruebas.ServicioUsuario.usuario)(this)).getInformacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pruebas.ServicioUsuario.getPeriodosResponse Pruebas.ServicioUsuario.usuario.getPeriodos(Pruebas.ServicioUsuario.getPeriodosRequest request) {
            return base.Channel.getPeriodos(request);
        }
        
        public string getPeriodos(string dni) {
            Pruebas.ServicioUsuario.getPeriodosRequest inValue = new Pruebas.ServicioUsuario.getPeriodosRequest();
            inValue.Body = new Pruebas.ServicioUsuario.getPeriodosRequestBody();
            inValue.Body.dni = dni;
            Pruebas.ServicioUsuario.getPeriodosResponse retVal = ((Pruebas.ServicioUsuario.usuario)(this)).getPeriodos(inValue);
            return retVal.Body.getPeriodosReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pruebas.ServicioUsuario.getPeriodosResponse> Pruebas.ServicioUsuario.usuario.getPeriodosAsync(Pruebas.ServicioUsuario.getPeriodosRequest request) {
            return base.Channel.getPeriodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pruebas.ServicioUsuario.getPeriodosResponse> getPeriodosAsync(string dni) {
            Pruebas.ServicioUsuario.getPeriodosRequest inValue = new Pruebas.ServicioUsuario.getPeriodosRequest();
            inValue.Body = new Pruebas.ServicioUsuario.getPeriodosRequestBody();
            inValue.Body.dni = dni;
            return ((Pruebas.ServicioUsuario.usuario)(this)).getPeriodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pruebas.ServicioUsuario.setContrasenaResponse Pruebas.ServicioUsuario.usuario.setContrasena(Pruebas.ServicioUsuario.setContrasenaRequest request) {
            return base.Channel.setContrasena(request);
        }
        
        public string setContrasena(string dni, string contrasena, string nuevaContrasena) {
            Pruebas.ServicioUsuario.setContrasenaRequest inValue = new Pruebas.ServicioUsuario.setContrasenaRequest();
            inValue.Body = new Pruebas.ServicioUsuario.setContrasenaRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.contrasena = contrasena;
            inValue.Body.nuevaContrasena = nuevaContrasena;
            Pruebas.ServicioUsuario.setContrasenaResponse retVal = ((Pruebas.ServicioUsuario.usuario)(this)).setContrasena(inValue);
            return retVal.Body.setContrasenaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pruebas.ServicioUsuario.setContrasenaResponse> Pruebas.ServicioUsuario.usuario.setContrasenaAsync(Pruebas.ServicioUsuario.setContrasenaRequest request) {
            return base.Channel.setContrasenaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pruebas.ServicioUsuario.setContrasenaResponse> setContrasenaAsync(string dni, string contrasena, string nuevaContrasena) {
            Pruebas.ServicioUsuario.setContrasenaRequest inValue = new Pruebas.ServicioUsuario.setContrasenaRequest();
            inValue.Body = new Pruebas.ServicioUsuario.setContrasenaRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.contrasena = contrasena;
            inValue.Body.nuevaContrasena = nuevaContrasena;
            return ((Pruebas.ServicioUsuario.usuario)(this)).setContrasenaAsync(inValue);
        }
    }
}
