//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorNotas.ServicioCalificacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.academico.ulasalle.com", ConfigurationName="ServicioCalificacion.calificacion")]
    public interface calificacion {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://services.academico.ulasalle.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServidorNotas.ServicioCalificacion.getNotasResponse getNotas(ServidorNotas.ServicioCalificacion.getNotasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServidorNotas.ServicioCalificacion.getNotasResponse> getNotasAsync(ServidorNotas.ServicioCalificacion.getNotasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://services.academico.ulasalle.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServidorNotas.ServicioCalificacion.getCalificacionesResponse getCalificaciones(ServidorNotas.ServicioCalificacion.getCalificacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServidorNotas.ServicioCalificacion.getCalificacionesResponse> getCalificacionesAsync(ServidorNotas.ServicioCalificacion.getCalificacionesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://services.academico.ulasalle.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServidorNotas.ServicioCalificacion.getMatriculaResponse getMatricula(ServidorNotas.ServicioCalificacion.getMatriculaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServidorNotas.ServicioCalificacion.getMatriculaResponse> getMatriculaAsync(ServidorNotas.ServicioCalificacion.getMatriculaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNotasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNotas", Namespace="http://services.academico.ulasalle.com", Order=0)]
        public ServidorNotas.ServicioCalificacion.getNotasRequestBody Body;
        
        public getNotasRequest() {
        }
        
        public getNotasRequest(ServidorNotas.ServicioCalificacion.getNotasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.academico.ulasalle.com")]
    public partial class getNotasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int periodo;
        
        public getNotasRequestBody() {
        }
        
        public getNotasRequestBody(string dni, int periodo) {
            this.dni = dni;
            this.periodo = periodo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNotasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNotasResponse", Namespace="http://services.academico.ulasalle.com", Order=0)]
        public ServidorNotas.ServicioCalificacion.getNotasResponseBody Body;
        
        public getNotasResponse() {
        }
        
        public getNotasResponse(ServidorNotas.ServicioCalificacion.getNotasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.academico.ulasalle.com")]
    public partial class getNotasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getNotasReturn;
        
        public getNotasResponseBody() {
        }
        
        public getNotasResponseBody(string getNotasReturn) {
            this.getNotasReturn = getNotasReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCalificacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCalificaciones", Namespace="http://services.academico.ulasalle.com", Order=0)]
        public ServidorNotas.ServicioCalificacion.getCalificacionesRequestBody Body;
        
        public getCalificacionesRequest() {
        }
        
        public getCalificacionesRequest(ServidorNotas.ServicioCalificacion.getCalificacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.academico.ulasalle.com")]
    public partial class getCalificacionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int periodo;
        
        public getCalificacionesRequestBody() {
        }
        
        public getCalificacionesRequestBody(string dni, int periodo) {
            this.dni = dni;
            this.periodo = periodo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCalificacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCalificacionesResponse", Namespace="http://services.academico.ulasalle.com", Order=0)]
        public ServidorNotas.ServicioCalificacion.getCalificacionesResponseBody Body;
        
        public getCalificacionesResponse() {
        }
        
        public getCalificacionesResponse(ServidorNotas.ServicioCalificacion.getCalificacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.academico.ulasalle.com")]
    public partial class getCalificacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getCalificacionesReturn;
        
        public getCalificacionesResponseBody() {
        }
        
        public getCalificacionesResponseBody(string getCalificacionesReturn) {
            this.getCalificacionesReturn = getCalificacionesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMatriculaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMatricula", Namespace="http://services.academico.ulasalle.com", Order=0)]
        public ServidorNotas.ServicioCalificacion.getMatriculaRequestBody Body;
        
        public getMatriculaRequest() {
        }
        
        public getMatriculaRequest(ServidorNotas.ServicioCalificacion.getMatriculaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.academico.ulasalle.com")]
    public partial class getMatriculaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int periodo;
        
        public getMatriculaRequestBody() {
        }
        
        public getMatriculaRequestBody(string dni, int periodo) {
            this.dni = dni;
            this.periodo = periodo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMatriculaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMatriculaResponse", Namespace="http://services.academico.ulasalle.com", Order=0)]
        public ServidorNotas.ServicioCalificacion.getMatriculaResponseBody Body;
        
        public getMatriculaResponse() {
        }
        
        public getMatriculaResponse(ServidorNotas.ServicioCalificacion.getMatriculaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.academico.ulasalle.com")]
    public partial class getMatriculaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getMatriculaReturn;
        
        public getMatriculaResponseBody() {
        }
        
        public getMatriculaResponseBody(string getMatriculaReturn) {
            this.getMatriculaReturn = getMatriculaReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface calificacionChannel : ServidorNotas.ServicioCalificacion.calificacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class calificacionClient : System.ServiceModel.ClientBase<ServidorNotas.ServicioCalificacion.calificacion>, ServidorNotas.ServicioCalificacion.calificacion {
        
        public calificacionClient() {
        }
        
        public calificacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public calificacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calificacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calificacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServidorNotas.ServicioCalificacion.getNotasResponse ServidorNotas.ServicioCalificacion.calificacion.getNotas(ServidorNotas.ServicioCalificacion.getNotasRequest request) {
            return base.Channel.getNotas(request);
        }
        
        public string getNotas(string dni, int periodo) {
            ServidorNotas.ServicioCalificacion.getNotasRequest inValue = new ServidorNotas.ServicioCalificacion.getNotasRequest();
            inValue.Body = new ServidorNotas.ServicioCalificacion.getNotasRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.periodo = periodo;
            ServidorNotas.ServicioCalificacion.getNotasResponse retVal = ((ServidorNotas.ServicioCalificacion.calificacion)(this)).getNotas(inValue);
            return retVal.Body.getNotasReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServidorNotas.ServicioCalificacion.getNotasResponse> ServidorNotas.ServicioCalificacion.calificacion.getNotasAsync(ServidorNotas.ServicioCalificacion.getNotasRequest request) {
            return base.Channel.getNotasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServidorNotas.ServicioCalificacion.getNotasResponse> getNotasAsync(string dni, int periodo) {
            ServidorNotas.ServicioCalificacion.getNotasRequest inValue = new ServidorNotas.ServicioCalificacion.getNotasRequest();
            inValue.Body = new ServidorNotas.ServicioCalificacion.getNotasRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.periodo = periodo;
            return ((ServidorNotas.ServicioCalificacion.calificacion)(this)).getNotasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServidorNotas.ServicioCalificacion.getCalificacionesResponse ServidorNotas.ServicioCalificacion.calificacion.getCalificaciones(ServidorNotas.ServicioCalificacion.getCalificacionesRequest request) {
            return base.Channel.getCalificaciones(request);
        }
        
        public string getCalificaciones(string dni, int periodo) {
            ServidorNotas.ServicioCalificacion.getCalificacionesRequest inValue = new ServidorNotas.ServicioCalificacion.getCalificacionesRequest();
            inValue.Body = new ServidorNotas.ServicioCalificacion.getCalificacionesRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.periodo = periodo;
            ServidorNotas.ServicioCalificacion.getCalificacionesResponse retVal = ((ServidorNotas.ServicioCalificacion.calificacion)(this)).getCalificaciones(inValue);
            return retVal.Body.getCalificacionesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServidorNotas.ServicioCalificacion.getCalificacionesResponse> ServidorNotas.ServicioCalificacion.calificacion.getCalificacionesAsync(ServidorNotas.ServicioCalificacion.getCalificacionesRequest request) {
            return base.Channel.getCalificacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServidorNotas.ServicioCalificacion.getCalificacionesResponse> getCalificacionesAsync(string dni, int periodo) {
            ServidorNotas.ServicioCalificacion.getCalificacionesRequest inValue = new ServidorNotas.ServicioCalificacion.getCalificacionesRequest();
            inValue.Body = new ServidorNotas.ServicioCalificacion.getCalificacionesRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.periodo = periodo;
            return ((ServidorNotas.ServicioCalificacion.calificacion)(this)).getCalificacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServidorNotas.ServicioCalificacion.getMatriculaResponse ServidorNotas.ServicioCalificacion.calificacion.getMatricula(ServidorNotas.ServicioCalificacion.getMatriculaRequest request) {
            return base.Channel.getMatricula(request);
        }
        
        public string getMatricula(string dni, int periodo) {
            ServidorNotas.ServicioCalificacion.getMatriculaRequest inValue = new ServidorNotas.ServicioCalificacion.getMatriculaRequest();
            inValue.Body = new ServidorNotas.ServicioCalificacion.getMatriculaRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.periodo = periodo;
            ServidorNotas.ServicioCalificacion.getMatriculaResponse retVal = ((ServidorNotas.ServicioCalificacion.calificacion)(this)).getMatricula(inValue);
            return retVal.Body.getMatriculaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServidorNotas.ServicioCalificacion.getMatriculaResponse> ServidorNotas.ServicioCalificacion.calificacion.getMatriculaAsync(ServidorNotas.ServicioCalificacion.getMatriculaRequest request) {
            return base.Channel.getMatriculaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServidorNotas.ServicioCalificacion.getMatriculaResponse> getMatriculaAsync(string dni, int periodo) {
            ServidorNotas.ServicioCalificacion.getMatriculaRequest inValue = new ServidorNotas.ServicioCalificacion.getMatriculaRequest();
            inValue.Body = new ServidorNotas.ServicioCalificacion.getMatriculaRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.periodo = periodo;
            return ((ServidorNotas.ServicioCalificacion.calificacion)(this)).getMatriculaAsync(inValue);
        }
    }
}
